name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node.js ${{ matrix.node-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - "12"
          - "*"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g npm@7
      - run: npm install
      - run: npm test
      - uses: codecov/codecov-action@v1
        with:
          name: Node.js ${{ matrix.node-version }}
